# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161212174138 on 2017-03-05 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.CharField(max_length=20000),
        ),
    ]
