# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161212174138 on 2017-03-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20170305_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.CharField(max_length=50000),
        ),
    ]
